apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yz8nxol4s-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yz8nxol4s-nodejs 
  name: yz8nxol4s-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yz8nxol4s-nodejs 
